-- 2025-05-13 복습 계정 생성

CREATE USER C##REVIEW IDENTIFIED BY REVIEW;
GRANT CONNECT, RESOURCE TO C##REVIEW;
ALTER USER C##REVIEW QUOTA UNLIMITED ON USERS;

DROP TABLE TB_USER;
CREATE TABLE TB_USER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(30) UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL
);
DROP SEQUENCE SEQ_USER;
CREATE SEQUENCE SEQ_USER;

DROP TABLE TB_BOARD;
CREATE TABLE TB_BOARD(
    BOARD_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(3000) NOT NULL
);

DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD;

BEGIN
    FOR I IN 1..100
    LOOP
        INSERT INTO TB_BOARD VALUES (SEQ_BOARD.NEXTVAL, '테스트 '||I, '테스트 '||I||'입니다');
    END LOOP;
END;
/

COMMIT;
ROLLBACK;
